version: '3.8'

services:

  app:
    build: 
      context: .
      dockerfile: Dockerfile.develop
    container_name: merchant-backend
    restart: always
    depends_on:
      - db
    ports:
      - "4000:4000"

  db:
    image: postgres:14
    container_name: postgres-merchant
    ports:
      - 5432:5432
    environment:
        POSTGRES_PASSWORD: 'postgres'
        POSTGRES_USER: 'postgres'
        POSTGRES_DB: 'merchant'
    volumes:
      - postgres:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres:
    name: merchant-db
